<?php


namespace App\Form;



use App\Data\SearchData;
use App\Entity\Etat;
use App\Entity\Site;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SearchForm extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('r', TextType::class,[
                    'label' => 'Le nom de la sortie contient : ',
                    'required' => false,
                    'attr' => [
                        'placeHolder' => 'Rechercher'
                    ]
                    ])

            ->add('site' ,EntityType::class,[
                'label'=> 'Site : ',
                'required'=> false,
                'class'=> Site::class,
                'expanded' => true,
                'multiple' => true,
            ])
            ->add( 'isInscrit', CheckboxType::class,[
                'label'=> 'Sortie à laquelle je suis inscrite',
                'required'=> false,
            ])
            ->add('organisateur',CheckboxType::class, [
                'label' => 'Sortie pour laquelle je suis organisateurs',
                'required' => false,
            ])


        ;
    }


    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
      $resolver->setDefaults([
        'data_class' => SearchData::class,
        'method' => 'GET',
        'crsf_protection' =>false
      ] );
    }

    public function getBlockPrefix()
    {
        return '';
    }
}
